### ISSUE TITLE
送信方法選択機能の追加

### ISSUE THREAD

**Issue by shallouweb** [hrl7/Chatbox#2]
chatboxでメッセージを送るときにenterを押して送信する方法とボタンをクリックして送信する方法選べるようにする。（例FaceBook）

**Comment by zigen** [comment]
issueのタイトルを "新規機能追加" だとなんの新規機能かパッとみて分かりづらいので, "送信方法選択機能の追加" とかがよい。

**Comment by zigen** [comment]
ナビゲーションバーにSettingを追加した。
Setting -> Edit -> 好きなpost methodを選択してupdate settingをクリックすると変更可能

**Comment by zigen** [comment]
あと左上のロゴから/に飛べるようにした

**Comment by shallouweb** [comment]
直した！
